import React, { useEffect, useMemo, useState } from 'react';
import WhistleDuck from '../components/WhistleDuck';
import { addScheduleItem, deleteScheduleItem, loadSchedule, saveSchedule, savePrefs, loadPrefs, updateScheduleItem } from '../lib/storage';
const MODES=[['pomodoro','Pomodoro 25/5'],['deep','Deep Work 50/10'],['boss','Boss Focus 90/20'],['reading','Reading 45/10'],['writing','Writing 30/5'],['exam','Exam 60/10'],['custom','Custom / reminder']];
export default function ScheduleScreen({ onHome,onTune,onStartFocus,onWhistle }){
  const [items,setItems]=useState(loadSchedule()); const prefs=loadPrefs(); const [notify,setNotify]=useState(Boolean(prefs.scheduleNotifications));
  const [title,setTitle]=useState(''); const [when,setWhen]=useState(()=>{const d=new Date(Date.now()+3600000);d.setSeconds(0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}); const[mode,setMode]=useState('pomodoro');
  const upcoming=useMemo(()=>items.filter(x=>!x.done&&new Date(x.when).getTime()>=Date.now()-60000).sort((a,b)=>new Date(a.when)-new Date(b.when)),[items]);
  useEffect(()=>{const t=setInterval(()=>{const now=Date.now();const due=loadSchedule().filter(x=>!x.done&&!x.alerted&&Math.abs(new Date(x.when).getTime()-now)<45000);if(!due.length)return;let next=loadSchedule();due.forEach(item=>{if(notify&&'Notification' in window&&window.Notification.permission==='granted')new window.Notification('VIBECADE schedule',{body:item.title||'Focus shift due'});next=next.map(x=>x.id===item.id?{...x,alerted:true}:x)});saveSchedule(next);setItems(next);},30000);return()=>clearInterval(t)},[notify]);
  const add=()=>{if(!title.trim()||!when)return;setItems(addScheduleItem({title:title.trim(),when:new Date(when).toISOString(),mode}));setTitle('')};
  const toggleNotifications=async()=>{let next=!notify;if(next&&'Notification'in window&&window.Notification.permission!=='granted'){const p=await window.Notification.requestPermission();next=p==='granted'}setNotify(next);savePrefs({...loadPrefs(),scheduleNotifications:next})};
  return <main className="room-screen schedule-room-screen"><div className="room-toolbar"><button onClick={onHome}>← LOBBY</button><span>ROOM 05</span><button onClick={onTune}>⚙ TUNE WORLD</button></div>
    <section className="schedule-head"><div><span className="kicker">DEPARTMENT OF WHEN</span><h1>SCHEDULE</h1><p>Plan focus shifts or reminders. If VIBECADE is open, the duck can announce them. Browser notifications are optional.</p></div><WhistleDuck active message={upcoming[0]?`Next: ${upcoming[0].title}`:'No appointments. Suspicious.'} onWhistle={onWhistle}/></section>
    <section className="schedule-layout"><div className="schedule-form"><label>WHAT<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Revise algorithms"/></label><label>WHEN<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><label>TYPE<select value={mode} onChange={e=>setMode(e.target.value)}>{MODES.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><button className="primary" onClick={add}>ADD TO DUCK'S CLIPBOARD</button><label className="schedule-notify"><input type="checkbox" checked={notify} onChange={toggleNotifications}/> Optional browser notifications</label><small>Notifications only fire when the browser allows them; the schedule itself is always stored locally.</small></div>
      <div className="schedule-list"><div className="panel-label">UPCOMING</div>{items.length===0&&<div className="empty-room">Nothing scheduled. The duck has started reorganising pencils.</div>}{[...items].sort((a,b)=>new Date(a.when)-new Date(b.when)).map(item=><article key={item.id} className={item.done?'done':''}><button className="schedule-check" onClick={()=>setItems(updateScheduleItem(item.id,{done:!item.done}))}>{item.done?'✓':'○'}</button><div><b>{item.title}</b><span>{new Date(item.when).toLocaleString()} · {item.mode}</span></div><div><button onClick={()=>{onStartFocus(item.mode);}}>START</button><button onClick={()=>setItems(deleteScheduleItem(item.id))}>×</button></div></article>)}</div></section>
  </main>;
}
