import React, { useEffect, useRef, useState } from 'react';
import { loadScores, saveScore } from '../lib/storage';

const GAME_META = {
  cat: ['CAT CATCH','Catch the cat before it teleports away.','30 SEC','PIXEL'],
  beat: ['BEAT TAP','Hit the pulse as it crosses the perfect zone.','20 SEC','ANY'],
  neon: ['NEON DODGE','Move between lanes and dodge incoming blocks.','30 SEC','CITY'],
  ink: ['INK REFLEX','Wait for the ink mark. Click only when it appears.','8 ROUNDS','MANGA'],
  panel: ['PANEL BREAKER','Smash the shown key before the panel expires.','30 SEC','COMIC'],
  glitch: ['GLITCH HUNT','Find the corrupted tile before it moves.','25 SEC','VOID'],
};

export default function MiniGame({ onClose, onSfx, voidUnlocked = false }) {
  const [game, setGame] = useState(null);
  const [scores,setScores]=useState(loadScores());
  const done=(id,score)=>setScores(saveScore(id,score));
  const ids=Object.keys(GAME_META).filter(id=>id!=='glitch'||voidUnlocked);
  return <div className="modal-backdrop arcade-modal" role="dialog" aria-modal="true" aria-label="Vibecade arcade"><div className="modal-card game-shell"><div className="modal-head"><div><span className="kicker">ARCADE BREAK / SHORT DISTRACTIONS ONLY</span><h2>INSERT DISTRACTION</h2></div><button onClick={onClose}>×</button></div>{!game ? <div className="game-menu expanded">{ids.map(id=>{const m=GAME_META[id];return <button className={`game-choice game-${id}`} key={id} onClick={()=>setGame(id)}><b>{m[0]}</b><span>{m[1]}</span><em>{m[2]} · {m[3]}</em><small>HI {scores[id]||0}</small></button>})}</div> : <Game id={game} onExit={()=>setGame(null)} onSfx={onSfx} onDone={score=>done(game,score)}/>}</div></div>;
}

function Game({id,...props}){if(id==='cat')return <CatCatch {...props}/>;if(id==='beat')return <BeatTap {...props}/>;if(id==='neon')return <NeonDodge {...props}/>;if(id==='ink')return <InkReflex {...props}/>;if(id==='panel')return <PanelBreaker {...props}/>;return <GlitchHunt {...props}/>;}
function Hud({score,time,onExit,label='TIME'}){return <div className="game-hud"><span>SCORE {String(score).padStart(2,'0')}</span><span>{label} {time}</span><button onClick={onExit}>EXIT</button></div>}
function End({score,onExit,onDone,text='ROUND COMPLETE'}){useEffect(()=>{onDone?.(score)},[]);return <div className="game-over"><b>{text}</b><span>{score} points</span><button onClick={onExit}>BACK TO ARCADE</button></div>}

function CatCatch({onExit,onSfx,onDone}){const[score,setScore]=useState(0),[time,setTime]=useState(30),[pos,setPos]=useState({x:45,y:45});useEffect(()=>{const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[]);const hit=()=>{if(!time)return;setScore(v=>v+1);onSfx?.('coin');setPos({x:7+Math.random()*82,y:10+Math.random()*72})};return <div><Hud score={score} time={time} onExit={onExit}/><div className="cat-game-stage">{time>0?<button className="game-cat" onClick={hit} style={{left:`${pos.x}%`,top:`${pos.y}%`}}>ฅ^•ﻌ•^ฅ</button>:<End score={score} onExit={onExit} onDone={onDone} text={score>=12?'CAT IMPRESSED':'CAT UNMOVED'}/>}</div></div>}

function BeatTap({onExit,onSfx,onDone}){const[score,setScore]=useState(0),[time,setTime]=useState(20),[phase,setPhase]=useState(0);const dir=useRef(1);useEffect(()=>{let raf;const loop=()=>{setPhase(v=>{let n=v+dir.current*1.55;if(n>=100){n=100;dir.current=-1}if(n<=0){n=0;dir.current=1}return n});raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>{cancelAnimationFrame(raf);clearInterval(t)}},[]);const tap=()=>{if(!time)return;const dist=Math.abs(phase-50);const pts=dist<6?3:dist<14?2:dist<24?1:0;setScore(v=>v+pts);onSfx?.(pts?'coin':'hit')};return <div><Hud score={score} time={time} onExit={onExit}/><div className="beat-stage"><div className="beat-track"><div className="beat-zone"/><div className="beat-orb" style={{left:`${phase}%`}}/></div>{time>0?<button className="tap-pad" onClick={tap}>TAP</button>:<End score={score} onExit={onExit} onDone={onDone}/>}</div></div>}

function NeonDodge({onExit,onSfx,onDone}){const[lane,setLane]=useState(1),[blocks,setBlocks]=useState([]),[time,setTime]=useState(30),[score,setScore]=useState(0);useEffect(()=>{const spawn=setInterval(()=>setBlocks(v=>[...v,{id:Date.now(),lane:Math.floor(Math.random()*3),y:0}]),650);const tick=setInterval(()=>{setBlocks(v=>{let hit=false;const next=v.map(b=>({...b,y:b.y+12})).filter(b=>{if(b.y>=88&&b.y<=100&&b.lane===lane)hit=true;return b.y<108});if(hit){onSfx?.('hit');setScore(s=>Math.max(0,s-2))}else setScore(s=>s+1);return next})},150);const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>{clearInterval(spawn);clearInterval(tick);clearInterval(t)}},[lane]);useEffect(()=>{const k=e=>{if(e.key==='ArrowLeft')setLane(v=>Math.max(0,v-1));if(e.key==='ArrowRight')setLane(v=>Math.min(2,v+1))};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[]);return <div><Hud score={score} time={time} onExit={onExit}/><div className="neon-stage">{time>0?<><div className="lane-lines"/><div className="neon-player" style={{left:`${16.6+lane*33.3}%`}}>▲</div>{blocks.map(b=><i key={b.id} className="neon-block" style={{left:`${16.6+b.lane*33.3}%`,top:`${b.y}%`}}/>)}<div className="lane-buttons"><button onClick={()=>setLane(v=>Math.max(0,v-1))}>←</button><button onClick={()=>setLane(v=>Math.min(2,v+1))}>→</button></div></>:<End score={score} onExit={onExit} onDone={onDone} text="CITY SURVIVED"/>}</div></div>}

function InkReflex({onExit,onSfx,onDone}){const[round,setRound]=useState(1),[score,setScore]=useState(0),[live,setLive]=useState(false),[message,setMessage]=useState('WAIT…');const startRef=useRef(0);useEffect(()=>{if(round>8)return;setLive(false);setMessage('WAIT…');const t=setTimeout(()=>{startRef.current=performance.now();setLive(true);setMessage('NOW!')},700+Math.random()*1800);return()=>clearTimeout(t)},[round]);const hit=()=>{if(round>8)return;if(!live){setScore(v=>Math.max(0,v-2));setMessage('TOO EARLY');onSfx?.('fail');setTimeout(()=>setRound(v=>v+1),500);return}const ms=performance.now()-startRef.current;const pts=ms<250?5:ms<400?3:ms<650?2:1;setScore(v=>v+pts);setLive(false);setMessage(`${Math.round(ms)}ms`);onSfx?.('coin');setTimeout(()=>setRound(v=>v+1),550)};return <div><Hud score={score} time={`${Math.min(round,8)}/8`} label="ROUND" onExit={onExit}/><div className="ink-stage">{round<=8?<button className={live?'ink-mark live':'ink-mark'} onClick={hit}><span>{message}</span></button>:<End score={score} onExit={onExit} onDone={onDone} text="INK DRIED"/>}</div></div>}

function PanelBreaker({onExit,onSfx,onDone}){const keys=['A','S','D','F','J','K','L'];const[target,setTarget]=useState('A'),[score,setScore]=useState(0),[time,setTime]=useState(30);const roll=()=>setTarget(keys[Math.floor(Math.random()*keys.length)]);useEffect(()=>{roll();const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[]);useEffect(()=>{const h=e=>{if(!time)return;if(e.key.toUpperCase()===target){setScore(v=>v+2);onSfx?.('coin');roll()}else if(/^[a-z]$/i.test(e.key)){setScore(v=>Math.max(0,v-1));onSfx?.('hit')}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[target,time]);return <div><Hud score={score} time={time} onExit={onExit}/><div className="panel-stage">{time>0?<><div className="comic-target">{target}!</div><p>PRESS THE PANEL KEY</p><div className="panel-keys">{keys.map(k=><button key={k} className={target===k?'active':''} onClick={()=>{if(k===target){setScore(v=>v+2);onSfx?.('coin');roll()}else onSfx?.('hit')}}>{k}</button>)}</div></>:<End score={score} onExit={onExit} onDone={onDone} text="PANEL SMASHED"/>}</div></div>}

function GlitchHunt({onExit,onSfx,onDone}){const[score,setScore]=useState(0),[time,setTime]=useState(25),[target,setTarget]=useState(0);useEffect(()=>{const m=setInterval(()=>setTarget(Math.floor(Math.random()*36)),750);const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>{clearInterval(m);clearInterval(t)}},[]);return <div><Hud score={score} time={time} onExit={onExit}/><div className="glitch-stage">{time>0?<div className="glitch-grid">{Array.from({length:36},(_,i)=><button key={i} className={i===target?'corrupt':''} onClick={()=>{if(i===target){setScore(v=>v+2);setTarget(Math.floor(Math.random()*36));onSfx?.('coin')}else{setScore(v=>Math.max(0,v-1));onSfx?.('hit')}}}>{i===target?'ERR':'01'}</button>)}</div>:<End score={score} onExit={onExit} onDone={onDone} text="SIGNAL RESTORED"/>}</div></div>}
